; =============================================================================
; platformio.ini — Dispositivo 1 (Esclavo IR con CRC-8)
; Trabajo Práctico N°3 — Comunicación de Datos
; =============================================================================
;
; Compilar : Ctrl+Alt+B
; Flashear : Ctrl+Alt+U
; Monitor  : Ctrl+Alt+S
;
; Si el ESP32 no entra en modo de programacion automaticamente,
; mantener presionado BOOT mientras aparece "Connecting..." y
; soltar cuando comience la transferencia.

[env:esp32dev]
platform         = espressif32
board            = esp32dev
framework        = arduino

monitor_speed    = 115200
upload_speed     = 921600
; Descomentar y ajustar si PlatformIO no detecta el puerto automaticamente:
upload_port    = COM3          ; Windows
; upload_port    = /dev/ttyUSB0  ; Linux
monitor_port = COM3

lib_deps =
    z3t0/IRremote @ ^4.7.1

build_flags =
    -DCORE_DEBUG_LEVEL=0

monitor_filters = esp32_exception_decoder