; =============================================================================
; platformio.ini — Dispositivo 2 (Maestro IR + Servidor Wi-Fi)
; Trabajo Práctico N°3 — Comunicación de Datos
; =============================================================================

[env:esp32dev]
platform         = espressif32
board            = esp32dev
framework        = arduino

monitor_speed    = 115200
upload_speed     = 921600
upload_port    = COM10
monitor_port = COM10

lib_deps =
    z3t0/IRremote @ ^4.7.1
    me-no-dev/AsyncTCP @ ^1.1.1
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    bblanchon/ArduinoJson @ ^7.2.0

build_flags =
    -DCORE_DEBUG_LEVEL=0

monitor_filters = esp32_exception_decoder